#pragma once

/*
 * Task core affinity (dual-core): PRO_CPU = 0, APP_CPU = 1.
 * LVGL pinned to APP_CPU so IDLE0 on PRO_CPU can run and feed task WDT.
 * App tasks pinned to PRO_CPU for clear separation (MISRA: named constants, no magic numbers).
 */
enum
{
    ESP32TOUCH_TASK_CORE_PRO = 0,
    ESP32TOUCH_TASK_CORE_APP = 1
};

enum
{
    SECONDS_PER_MINUTE = 60,
    ESP32TOUCH_LVGL_DRAW_BUFFER_LINE_COUNT = 20,
    ESP32TOUCH_LVGL_TICK_PERIOD_MS = 2,
    ESP32TOUCH_LVGL_TASK_STACK_SIZE_BYTES = (16 * 1024),
    ESP32TOUCH_LVGL_TASK_PRIORITY = 2,
    ESP32TOUCH_LVGL_TASK_CORE_ID = ESP32TOUCH_TASK_CORE_APP,
    ESP32TOUCH_LVGL_TASK_MIN_DELAY_MS = 1,
    ESP32TOUCH_LVGL_TASK_MAX_DELAY_MS = 500,
    ESP32TOUCH_LVGL_LOCK_TIMEOUT_MS = 100,
    ESP32TOUCH_APP_TASK_STACK_SIZE_BYTES = (4 * 1024),
    ESP32TOUCH_APP_TASK_PRIORITY = 4,
    ESP32TOUCH_APP_TASK_CORE_ID = ESP32TOUCH_TASK_CORE_PRO,
    ESP32TOUCH_APP_UPDATE_PERIOD_MS = 2000
};
